### ISSUE TITLE
Correção - Script de Banco de Dados Inicial

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#109]
Criação do script inicial da base de dados

**Comment by rafaeljcg20** [comment]
Plano de implantação ou mudança:
1 trocar o backend"api-maisum" para branch: hotfix/script-data-base
2 Fazer backup da base de Dados atual: sudo mv database database-bkp-2023-01-26-v-1
3 docker compose up

**Comment by matheusz061df** [comment]
indetifiquei um erro
prescisa colocar o sudo e tirar o mv
alternaiva para solucionar- sudo mv database database-bkp-2023-01-26-v-1

**Comment by rafaeljcg20** [comment]
Corrigido

**Comment by matheusz061df** [comment]
indentifiquei um erro :
no terminal o doscker so fuciona em minusculo pra nao acontecer um erro sintaxe

**Comment by rafaeljcg20** [comment]
corrigido também

= )

**Comment by matheusz061df** [comment]
Fiz todos os testes possiveis e aparentemente todo o sitema funcionou perfeitamente

**Comment by rafaeljcg20** [comment]
Item de backlog concluído. Vou realizar o merge com master, tentar lançar a versão e quando o servidor do backend estiver disponivel realizar a publicação e importação dos dados para o BD novo.

Obrigado Matheus e Isaque!
@isaqu33 @matheusz061df
