### ISSUE TITLE
Cadastro de Atividades(DashBoard)

### ISSUE THREAD

**Issue by dougs007** [sara-nossa-terra/engajamento#12]
Funcionalidade da tela:

Critérios de aceitação:

- [X] Listar primeiramente o nome do Líder. (Verificar se deve ter algo diferenciando)
- [X] Listar apenas as pessoas ajudados para o líder logado.
- [x] Mudar a data e mudar os registros mediante a data selecionada.
- [x] Ação de afirmar positivamente ou negativamente sobre ter realizado a atividade ou não.

![Cadastro de Atividades-Prototipo.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/be3ce1f1-820a-456f-abbe-5867017e23fa)

**Comment by dougs007** [comment]
@sara-nossa-terra/technology-squad-snt, favor verificar e caso seja necessário, implementar/modificar.

**Comment by rafaeljcg20** [comment]
![Cadastro de Atividades-Prototipo.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/8923c342-a549-43e7-ae6b-7291516269ba)

**Comment by rafaeljcg20** [comment]
Desafios do Grupo do Whatsapp:
- [X] ( Desafio 1 ) - fazer os métodos ajax que carregam as pessoas ajudadas na lista da Tela Cadastro de Atividades do Líder.
- [x] ( Desafio 2 ) Fazer métodos ajax que carregam os nomes e hora das Atividades na Tela Cadastro de Atividades do Líder.

**Comment by rafaeljcg20** [comment]
Boa tarde Pessoal, novamente parabenizo a evolução do código e atualização das funções nativas de browsers utilizadas para invocar as requisições do sistema, porém ao realizar testes notei o seguinte erro que acredito que seja fácil de resolvermos:

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/e5efcd05-2def-461a-a9b8-d7cd37df0bc2)

@rodrigodiasnoronha , @Paulophmp @dougs007
