### ISSUE TITLE
Refatoração App Mobile - Tela de Login

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#41]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/90cede91-ad4d-4854-a2c7-55c2f88d4032)

**Comment by thiagojsef** [comment]
Protótipo navegável de baixa fidelidade do sistema de Login do app
https://marvelapp.com/6cdbhb9

Algumas telas não foram prototipadas pois ainda não foram definidos quais serão os seus requisitos.
