### ISSUE TITLE
[CADASTRO DE LÍDERES] PERFIL DE USUÁRIO

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#59]
Favor, inserir a informação Perfil na tela Gerenciar Líderes podendo ser os seguintes valores número 1 para Administrador e número 2 para Líder. Obs: Criar uma tabela perfil com os campos código e nome;

RN - Quando o usuário for do tipo Administrador ele não deve ter vinculo com líder; Obs: Por favor gravar o valor 'NULL' no campo Lider_id da tabela de líder do banco de dados;

RA - O sistema só deve mostrar o campo 'Líder' quando a opção 'Perfil' estiver com o valor 'Líder';

Papeis:
RN - Quando o perfil do usúário autenticado for Líder o sistema não deve mostrar o Menu 'Atividades';
RN - Quando o perfil do usuário autenticado for líder o sistema só deve permitir cadastrar Líder para o usuário Logado. Sugestão: Não exibir a opção 'Líder';

LEGENDA:
RA - REGRA DE APRESENTAÇÃO - Comportamento visual de uma parte do sistema.
RN - REGRA DE NEGÓCIO - Detalhe da funcionalidade, comportamento e ou regras que abrangem todo o sistema.

**Comment by dougs007** [comment]
- [X] Ao criar um líder é necessário informar o perfil_id, caso seja perfil_id = 1 (Administrador ), o backend setará null para a coluna lider_id, conforme RN, caso seja perfil_id = 2, o backend não faz nada, logo, o que vier setado da requisição como lider_id será gravado ao banco de dados.

- [X] Implementação de perfil no endpoint "/me";
- [X] Implementação de perfil no endpoint "/leaders";
- [X] Implementação de perfil no endpoint "/helpedPersons";

**Comment by dougs007** [comment]
@rodrigodiasnoronha Agora acho que só falta a implementação no mobile para a entrega da feature.

PS: always branch develop full atualizada.
