### ISSUE TITLE
Avatar - Foto do Líder

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#61]
Inserir possíbilidade de inserir foto no cadastro do líder para exibir nos relatórios

**Comment by rafaeljcg20** [comment]
Tarefas acordadas em paralelo:
1 - Atualização do Laravel;
2 - Solução de autenticação com Firebase e mudanças no frontend;

**Comment by rafaeljcg20** [comment]
@isaqu33 , por favor me envie os dados de envio da requisição:
Ex: post Envio/Request {
 name,
 bin,
 size,
}

Retorno

{
 str_url_image
}

**Comment by rafaeljcg20** [comment]
@Jonaathan-Santos  @isaqu33 

Foi realizado acordo que o arquivo será enviado pra "API-Backend" no formato base64 e o nome do parametro/campo da requisição que será enviada a foto será  "image"

**Comment by rafaeljcg20** [comment]
Plano de Implantação e Mudança:
1 - Executar Script de Banco de dados: 
2 - Alterar para a Branch: release/2.1.0 (Antiga: api/docker/postgres/scripts/01-photo-leader)
3 - Atualizar apk na Google e Apple Store

**Comment by rafaeljcg20** [comment]
@Jonaathan-Santos 

Concluiu a parte do frontend de upload de foto e vai continuar a implementação no backend pra verificar como está chegando o arquivo

**Comment by rafaeljcg20** [comment]
@isaqu33 ajustando a tela de relatório layout e preparação pra exibição da foto.

**Comment by rafaeljcg20** [comment]
@isaqu33 e @Jonaathan-Santos solucionaram o problema de envio de imagem(arquivo) frontend. Foi identificado que o backend não estava recuperando a imagem da forma que o frontEnd estava enviando.

**Comment by rafaeljcg20** [comment]
Impedimento resolvido de upload de arquivos.

**Comment by rafaeljcg20** [comment]
concluída a implementaçao do endpoint da api para retornar a imagem salva.

**Comment by rafaeljcg20** [comment]
Começamos os testes, mas combinamos de ajustar a codificação que estava pegando um arquivo externo de imagem e colocar dentro do frontend para nosso App.

Também combinamos de fazer um script SQL para fazer a mudança de estrutura que acompanha o pacote de atualização da funcionalidade de inserir foto no líder

**Comment by rafaeljcg20** [comment]
Impedimento: Alinhamento de scripts SQL para mudanças em produção de feature e Fixs

**Comment by isaqu33** [comment]
https://images.zenhubusercontent.com/220815808/9b6c146d-b0cd-4c46-af29-64cfbaa43d9d/testesfeature_photolider.mp4


De acordo com o video, feature testada e tudo funcionando perfeitamente!!

**Comment by rafaeljcg20** [comment]
shoooooooooooooooow de mais!

parabéns a todos os envolvidos @Jonaathan-Santos @WarlenFerreira @isaqu33 

Vou fazer o merge com a develop, vamos reunir todos os itens de backlog que estão em "Feito" e fazer o merge na master.

Obs: Quando nosso servidor backend voltar, faremos o deploy imediatamente em produção lançando também uma versão nova na loja da Google Play

**Comment by rafaeljcg20** [comment]
Boa noite pessoal( @WarlenFerreira @Jonaathan-Santos @isaqu33 ),

Foi necessário mudar o caminho do arquivo SQL contendo as mudanças de banco de dados para esse item de backlog para esse local "api/docker/postgres/scripts/1-photo-leader"

Obs: Para ficar em conformidade com item de backlog "Correção - Script de Banco de Dados Inicial#109"

**Comment by rafaeljcg20** [comment]
@isaqu33 e @Jonaathan-Santos acredito que Identifiquei um erro ao tentar criar um novo Líder sem anexar a foto. O Resultado foi que o sistema informou que o líder foi criado com sucesso, porém não salvou os dados e não apresentou o novo lider na lista de Líderes após a mensagem de sucesso.

Segue o vídeo e a imagem de log do backend pra ajudar a reproduzir e identificar o problema:


https://images.zenhubusercontent.com/220815808/21712f78-9a74-4f62-bff4-0ea3638bd02e/screen_recording_20230130_204746_expo_go.mp4

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/04dc2062-c41f-40c3-8ac3-e464e69008ae)

**Comment by rafaeljcg20** [comment]
Pessoal, como a demanda já tinha sido testada e verificada pelo Isaque... Então eu já gerei uma branch release para publicação em produção, então deveremos agora fazer todos os ajustes nas branchs releases tanto do frontend quanto do backend caso seja necessário.

Segue o nome da branch release do backendo e do fronted:
**release/2.1.0**

@isaqu33 @Jonaathan-Santos

**Comment by isaqu33** [comment]
Conforme foi apontado, bug ajustado.

obs: 
*Foi feito um ajuste no "response" da solicitação HTTP do metodo POST no FrontEnd. 
*Foi feito um ajuste na entity do controler de criar Leder!!

**Comment by rafaeljcg20** [comment]
![erro salvar novo lider - teste vazio.jpeg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/ca0e6595-64b6-4f67-a52f-e037d04292f9)@isaqu33 

Quando eu tento fazer o fluxo básico de inserir líder preenchendo o minimo de campos possíveis que são obrigatórios e aperto no botão "Adicionar" o sistema não salva as informações e nem volta para a tela de lista.

**Comment by rafaeljcg20** [comment]
Quando eu tento fazer o fluxo básico de inserir líder digitando o máximo de caracteres possíveis em todos os campos e clicando em "Adicionar", o sistema retorna um erro ao tentar salvar.

Obs: Parece não existir validação de número máximo de caracteres no frontend e também no log do backend não parece existir validação máxima dos campos.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/778aeb12-6b1c-4f29-ac38-9d841ac4d72f)

@isaqu33

**Comment by rafaeljcg20** [comment]
Ao testar o fluxo básico inserir o líder com foto realizando o preenchimento apropriado de todos os campos e clicando no botão "Adicionar" o sistema não realiza ação nenhuma e nem exibe erro na tela. Esperava-se que o sistema criasse o usuário novo inserindo a foto que ele escolheu e retornasse para a lista com os dados do novo usuário.

@isaqu33 
![erro salvar novo lider - teste fluxo básico inserir com foto.jpeg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/fdebe002-ebc4-4326-a4c0-9d7e0405bb8f)

**Comment by isaqu33** [comment]
https://images.zenhubusercontent.com/220815808/ca48474a-a230-4288-b9fd-052adb4524a7/screen_recording_20230213_173519_expo_go.mp4



Conforme acordado, alteração realizada no inpute, onde foi colocado maximo de caracteres..

**Comment by rafaeljcg20** [comment]
Resolvido !

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/a219f3de-4801-45d0-9dda-f6c18daee37a)

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/141e3b75-4eee-46b8-8de3-2fdcac1c4ee9)

Resolvido 

Obs: Ainda precisa fazer validação no Backend.

**Comment by rafaeljcg20** [comment]
foi encontrado mais um erro.

Ao inserir uma senha diferente do campo confirmação de senha, o sistema exibe o campo em vermelho , porém não exibe a menssagem correta para o usuáriopoder entender e resolver a falha no preenchemimnento
@isaqu33 @joaovictodesousa 

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/1818214a-7822-4a2a-97b3-870c9a27dced)

**Comment by rafaeljcg20** [comment]
@joaovictodesousa A correção desse bug foi colocado em outro item de backlog por ser um recurso novo que o sistema não contava até esse momento, embora seja um requisito não funcional importantissímo.

**Portanto solicito que a demanda seja testada sem levar em consideração esse último erro de texto de validação.**
@matheusz061df

**Comment by maiconrit** [comment]
fiz o teste com maximo de  caratires e  achei esse  erro:

![Screenshot_20230219-172624_Expo Go.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/e229be70-9058-4ae1-8c03-888214818546)

![image.png](https://images.zenhubusercontent.com/632729ac30122bc300ff2498/0fcfccc8-9d04-467a-8656-c1684496794b)

**Comment by rafaeljcg20** [comment]
Foi verificado que o único campo que suporta o máximo de 200 caracteres é o campo de nome do líder, e ao tentar reproduzir o erro tanto no emulador quanto no próprio celular, o sistema não apresentou falhas.

Observação: Suspeita-se que o teste foi reaizado com arquivos de cache desatualizados que impediram o sistema de limitar a quantidade de caracteres do formulário. Portanto o item de backlog irá retornar para o estado de Teste e desconfiamos que não tem erro nenhum.

**Comment by rafaeljcg20** [comment]
Foi detectado um erro na tela de edição de líder.

Ao tentar editar o campo nome do líder para "z" em um cadastro com número de telefone "(61) 4444-4444" , o sistema marcou de vermelho o campo telefone. Esperava-se que como o valor do telefone "(61) 4444-4444" já estava salvo além de ser um número válido, o sistema então deveria ter permitido salvar os novos dados.

Observações: Após clicar no campo de telefone o sistema parou de marcar de vermelho e até permitiu salvar, porém devemos ajustar o problema de validação ao acionar o botão salvar conforme as condições descritas acima.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/edcf3565-1f85-4446-ae24-bf17d08bc558)

**Comment by rafaeljcg20** [comment]
Foi corrigido o erro na tela de edição de líder relacionando ao campo telefone

@joaovictodesousa @matraf123 e @matheusz061df , por favor realizarem os testes para finalizarmos a demanda.

**Comment by WarlenFerreira** [comment]
branch testada e funcionando perfeitamente, nos teste de adição de lider e edição do lider criado, não foi apresentado nenhum erro. sobre o erro do numero do telefone também correu tudo bem.

**Comment by rafaeljcg20** [comment]
Release verificada novamente e finalizando.

Muito Obrigado a todos os envolvidos @Jonaathan-Santos @isaqu33 @WarlenFerreira @matheusz061df @joaovictodesousa @maiconrit @matraf123
