### ISSUE TITLE
Tela de Consolidação - Exibir apenas pessoas ajudadas cadastradas(inseridas) no periodo

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#95]
Na Tela de Consolidação e dentro de Atividades exibir apenas pessoas ajudadas cadastradas(inseridas) no periodo exibido;

**Comment by rafaeljcg20** [comment]
Esse item só deverá ser implantada após o atendimento do item "Tela de Consolidação - Permitir incluir no Periodo Pessoa Ajudada em períodos anteriores"

**Comment by rafaeljcg20** [comment]
Branch: hotfix-consolidacao-pessoas-ajudadas-no-periodo

**Comment by rafaeljcg20** [comment]
Apenas Backend branch: hotfix-consolidacao-pessoas-ajudadas-no-periodo

**Comment by rafaeljcg20** [comment]
Implementação foi concluída

Porém lembrando que essa correção só poderá ser publicada depois do item de trabalho que permite incluir no Periodo Pessoa ajudada. Portanto essa branch não pode ser mergeada com master por enquanto;

**Comment by WarlenFerreira** [comment]
Branch testada e exibindo pessoas cadastradas somente dentro da semana cadastrada!
