### ISSUE TITLE
Tela de Pessoas Ajudadas, Tela de Líderes e Tela de Consolidação(principalmente) Inclusão de ícone com link direto para realizar Ligação

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/engajamento#96]
Tela de Pessoas Ajudadas, Tela de Líderes e Tela de Consolidação(principalmente) Inclusão de ícone com link direto para realizar Ligação

**Comment by WarlenFerreira** [comment]
teste

**Comment by rafaeljcg20** [comment]
Warlen está fazendo essa tarefa. 

Obs: Ainda com dificuldades de acesso ao Kanban e finalizar configuração do aplicativo no ambiente local

**Comment by rafaeljcg20** [comment]
Testando...

**Comment by rafaeljcg20** [comment]
Branch: feature-botao-ligacao

**Comment by rafaeljcg20** [comment]
Teste na tela de consolidação oK

Segue evidência:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/5ec397b7-530a-4487-80ff-f066b17bf6bd)

**Comment by rafaeljcg20** [comment]
@WarlenFerreira , ficou faltando só colocar a funcionalidade de ligação nas telas Líderes e Vidas conforme evidência abaixo:

@WarlenFerreira , poderia colocar pra gente pra eu poder refazer os testes?

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/7c6e7278-bcef-40ca-97e9-16be5741a4a1)

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/ac93e159-e4d8-4ed2-8d4d-a872ece725dc)

**Comment by WarlenFerreira** [comment]
@rafaeljcg20  Update realizado, botão de ligação adicionado nas telas de Lideres e Vidas, pronto para teste!

**Comment by rafaeljcg20** [comment]
Obrigado primão! @WarlenFerreira 

Funcionalidade testada, as evidências estão em anexo! 

Por favor peça o Pull request para a branch Develop e vamos pra próxima!
![Screenshot_20221013-165822_Expo Go.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/991c8b8b-b2ca-4c27-b4b7-421a95724601)
![Screenshot_20221013-165814_Expo Go.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/92906379-5b2a-4d0e-9fb2-d8ea13b18a71)
